### ISSUE TITLE
我居然被踢出 workspace

### ISSUE THREAD

**Issue by dou4cc** [simon300000/996icu-slack-recorder#2]
发生什么了?

**Comment by simon300000** [comment]
您似乎是因为开#esu 而被管理 Deactivated。

**Comment by zhangsanlisiwangwuzhaoliu** [comment]
请问您为何unarchived #esu 频道？

**Comment by dou4cc** [comment]
@simon300000 想扩就写进你的 Readme 吧. 另, 996icu/996.ICU Readme 的 Slack 邀请无效.

@zhangsanlisiwangwuzhaoliu 因为任何人都能 unarchive.

**Comment by simon300000** [comment]
扩？
